// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_sraplus_TMBExports
#include <TMB.hpp>
#include "sraplus_tmb.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "sraplus_tmb") {
    return sraplus_tmb(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
