# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
dist: trusty
cache: packages
r_check_args: --no-vignettes

env:
  global:
    - CXX14 = g++ # or clang++ if you have that
    - CXX14FLAGS = -O3