language: r
r: devel
sudo: TRUE
dist: trusty

cache:
  - packages
  - ccache

warnings_are_errors: FALSE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev
  
before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  # optionally add our launchpad repo, but not needed here
  # - sudo add-apt-repository -y ppa:edd/r-3.5
  - ./run.sh bootstrap