# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sraplus <- function(catches, rs, ms, init_deps, ks, qs, sigma_procs, drawdex, index_t, sigma_obs, log_final_u, log_final_u_cv, index_years, u_years, draws, n_keep, b_ref_type, fit_index, use_final_u, log_final_ref, sigma_dep, plim, u_prior, u_priors, sigma_u) {
    .Call(`_sraplus_sraplus`, catches, rs, ms, init_deps, ks, qs, sigma_procs, drawdex, index_t, sigma_obs, log_final_u, log_final_u_cv, index_years, u_years, draws, n_keep, b_ref_type, fit_index, use_final_u, log_final_ref, sigma_dep, plim, u_prior, u_priors, sigma_u)
}

